GET http://localhost:5000/todos

###

POST  https://todoapp-7jzr.onrender.com/todo/new
Content-Type: application/json

{
    "title": "Order ",
    "description":"Ordering pizza from MCDonalds"
}

###

DELETE  https://todoapp-7jzr.onrender.com/todo/delete/64f84cd042855c89653d1449

###
GET https://todoapp-7jzr.onrender.com/todo/complete/64f84d7ed54fbd35c392d94b

###
PUT https://todoapp-7jzr.onrender.com/todo/update/64f84d7ed54fbd35c392d94b
Content-Type: application/json

{
    "title": "Order pizza",
    "description":"Ordering burger from burger king"
}